### ISSUE TITLE
Teilweise Abschaltung der Router zur Lokalisierung des Problems?

### ISSUE THREAD

**Issue by kreativmonkey** [FreifunkMYK/Bugtracker-Dummy#17]
Die Idee ist aufgekommen das wir das Netz durch das eliminieren der Keys teilweise abschalten könnten.

Kurz angerissen:

- Alle Nodes abschalten und dann stückweise wieder aktivieren und schauen ab wann das Problem auftritt.
- Abschaltung wäre möglich nach Router Modellen und Firmware

**Comment by adlerweb** [comment]
Router lassen sich remote nicht abschalten. Es lassen sich nur VPN-Verbindungen kappen, das ist aber eher aufwändig da man immer alle VPN-Verbindungen der Wolke erwischen muss (also z.B. komplett Mayen oder komplett Oberwesel), andernfalls würden die "abgeschalteten" Router weiter über das WLAN-Mesh ihre Routen übertragen.

**Comment by adlerweb** [comment]
Da war so ein Fork seit Eröffnung des Tickets...
