### ISSUE TITLE
Keine Nightly-Firmware auf firmware.freifunk-myk.de

### ISSUE THREAD

**Issue by GitNorb** [FreifunkMYK/Bugtracker-Dummy#21]
Die neugebaute Nightly-Firmware von Niyawe wird nicht auf firmware.freifunk-myk.de übertragen.

**Comment by adlerweb** [comment]
Wie ist der aktuelle Trigger-Dateiname? /tmp/ffmyk-sync-NORMAL?

**Comment by adlerweb** [comment]
@niyawe sagt ffmyk-sync-NORMAL - Eingetragen und manuell ausgelöst. Synct.
