### ISSUE TITLE
Lange Wartezeit der Routen bei DHCP-Requests

### ISSUE THREAD

**Issue by GitNorb** [FreifunkMYK/Bugtracker-Dummy#23]
Nach dem eintritt ins Freifunk-Netz als Client dauert es bis zu 15 Minuten, bis die ipv6-Routen bei meinem Rechner eintreffen. Dadurch kann ich nicht direkt auf die Freifunk-Knoten zugreifen.

**Comment by adlerweb** [comment]
Site? Gateway? Router?
Sofern sich da in letzter Zeit nichts geändert hat wird das v6 vom lokalen Router announced

**Comment by GitNorb** [comment]
Router brauchen momentan lange bis sie die 2. Adresse bekommen.
Niklas sagte, dass das Problem sich bald durch die Umstellung auf FF-Rheinland behebt.

**Comment by GitNorb** [comment]
Erledigt. Problem besteht nicht mehr
