### ISSUE TITLE
Nightly Firmware wird nicht gebaut

### ISSUE THREAD

**Issue by GitNorb** [FreifunkMYK/Bugtracker-Dummy#25]
Der letzte commit im gluon-git ist vor 22 Stunden passiert. Die Firmware ist aber noch von vor 6 Tagen.

**Comment by adlerweb** [comment]
Ist auch so im Status zu sehen. 
```
/home/buildbot/ffmyk/slave/runtests/build/lede/staging_dir/hostpkg/bin/lua: .../slave/runtests/build/lede/../scripts/check_site.lua:62: bad argument #1 to 'unpack' (table expected, got string)
stack traceback:
	[C]: in function 'unpack'
	.../slave/runtests/build/lede/../scripts/check_site.lua:62: in function 'loadvar'
	.../slave/runtests/build/lede/../scripts/check_site.lua:83: in function <.../slave/runtests/build/lede/../scripts/check_site.lua:82>
	(tail call): ?
	.../slave/runtests/build/lede/../scripts/check_site.lua:150: in function 'need_table'
	stdin:1: in main chunk
	[C]: in function 'dofile'
	.../slave/runtests/build/lede/../scripts/check_site.lua:187: in main chunk
	[C]: ?
postinst script ./usr/lib/opkg/info/gluon-config-mode-geo-location-map.postinst has failed with exit code 1
```
Müsste mal wer Site/Module mit den Änderungen aus gluon-trunk aktualisieren um wieder dagegen bauen zu können

**Comment by niyawe** [comment]
> Ist auch so im Status zu sehen.

kannst du mir mal die ipv6 adresse des buildbot geben?

**Comment by adlerweb** [comment]
Später - ~~wollte den nächste Woche in die andere Hood ziehen, da ändert sich das ohnehin nochmal alles.~~ hatte den zum Test letzte woche an die neue Hood gehangen, daher aktuell nix festes.

**Comment by GitNorb** [comment]
Hat sich erledigt, da die jetzt auf einem anderen Server liegen
